# Generated by Django 4.0.1 on 2022-01-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='productdes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bookingdatefrom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bookingdateto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bookingid',
        ),
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='productprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdatefrom', models.DateField(default='', max_length=100)),
                ('bookingdateto', models.DateField(default='', max_length=100)),
                ('bookeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
