# Generated by Django 4.0.1 on 2022-02-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_product_productdes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
