# Generated by Django 4.0.1 on 2022-02-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_status_alter_product_productdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='authN',
            field=models.CharField(default='', max_length=100),
        ),
    ]
