# Generated by Django 4.0.1 on 2022-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_seller_authn'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(max_length=100, default=''),
        ),
    ]
