# Generated by Django 4.0.1 on 2022-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
