# Generated by Django 4.0.1 on 2022-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authN',
            field=models.CharField(default='', max_length=100),
        ),
    ]
